services:
  java:
    build:
      context: ./java-container
    volumes:
      - ..:/workspace:cached
    command: /bin/sh -c 'while sleep 1000; do :; done'

  jenkins:
    build:
      context: ./jenkins-container
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home"

volumes:
  jenkins_home: {}
