FROM goharbor/harbor-core:v2.10.0

# Exponer los puertos necesarios para Harbor
EXPOSE 80 443 4443

# Definir el directorio de trabajo
WORKDIR /harbor

# Ejecutar Harbor al iniciar el contenedor
CMD ["/entrypoint.sh"]
